#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service all
PROCESS_NAME="baserow-frontend"

export MEDIA_URL=${MEDIA_HOSTNAME}
export PUBLIC_BACKEND_DOMAIN="${API_HOSTNAME}"
export PUBLIC_BACKEND_URL="${API_PROTOCOL}://${API_HOSTNAME}"
export PUBLIC_WEB_FRONTEND_DOMAIN="${APPLICATION_HOSTNAME}"
export PUBLIC_WEB_FRONTEND_URL="${APPLICATION_PROTOCOL}://${APPLICATION_HOSTNAME}"
export PRIVATE_BACKEND_URL="${INTERNAL_API_PROTOCOL}://${INTERNAL_API_HOST}:${INTERNAL_API_LISTEN_PORT}"

print_info "Starting Baserow frontend"
cd /app/web-frontend/
./node_modules/.bin/nuxt start